### ISSUE TITLE
Pow operator

### ISSUE THREAD

**Issue by dakk** [dakk/qlasskit#23]
Implement the `ast.Pow` operator (**) between a variable and an integer constant. 
Since a ** n == a * a * ... * a, we implement this operator with a rewriting rule in `ast2ast`.

The rewriting rule should be placed in the class `AstRewriter` (https://github.com/dakk/qlasskit/blob/master/qlasskit/ast2ast.py#L137), overriding the method `visit_Pow`, and rewriting the pow as multiplications. 

- Check that `n` is an ast.Constant, positive integer
- If overriding `visit_Pow` won't work, override `visit_BinOp` instead and check if the expression is a `ast.Pow`

Please read [**CONTRIBUTING.md**](https://github.com/dakk/qlasskit/blob/master/CONTRIBUTING.md) before contributing.

**Comment by Youngcius** [comment]
I would like to try to solve this issue @dakk  Could you assign that to me

**Comment by dakk** [comment]
> I would like to try to solve this issue @dakk Could you assign that to me

Done, let me know if you have any question 👍

**Comment by dakk** [comment]
@Youngcius I unassigned the issue, since according to rules, A Issue is assigned to a contributor if contributor's PR gets successfully approved by the maintainer. I'm sorry for the confusion.

**Comment by Youngcius** [comment]
I see! Thanks for your info

**Comment by dakk** [comment]
@tomv42 thank you for the contribution, I merged the pull request after I made just a tiny edit, by using `Qtype.fill` instead of `pad_operand` (https://github.com/dakk/qlasskit/commit/d8b299efc40205cc1f6a75a39b9cc192fcc092d0).

Please comment this issue so I'm able to assign it to you.

**Comment by tomv42** [comment]
Thanks for merging the pull request! I enjoyed working on it and found the project very interesting.
