### ISSUE TITLE
py2qasm cli tool

### ISSUE THREAD

**Issue by dakk** [dakk/qlasskit#26]
Create a cli tool in the [`qlasskit/tools`](https://github.com/dakk/qlasskit/tree/master/qlasskit/tools) package called `py2qasm` that receives a python script (file or stdin) in input and outputs qasm code. The python script should contain at least one qlassf function. 

- If not specified by --input-file/-i, read from stdin (-).
- If not specified by --entrypoint/-e, func_name is the last qlassf defined.
- If not specified by --output/-o, output to stdout
- If not specified by --compiler/-c use internal compiler (or tweedledum)
- If not specified by --qasm-version/-q use v3 qasm version

```py2qasm -i pyfile [-e func_name] [-c internal] -o qasm_file```

Provide also:
- `-h\--help` for usage
- `-v\--version` for qlasskit version

Requirements:
- Code should be placed on [`qlasskit/tools`](https://github.com/dakk/qlasskit/tree/master/qlasskit/tools)
- Use [`argparse`](https://docs.python.org/3/library/argparse.html) for argument parsing
- Use [`qlasskit.tools.utils`](https://github.com/dakk/qlasskit/blob/master/qlasskit/tree/master/qlasskit/tools/utils.py) for getting qlassfs from file / string 
- A test case must be provided in [`test_tools.py`](https://github.com/dakk/qlasskit/blob/master/test/test_tools.py)
- Keep an eye on issue #28 

Please read [**CONTRIBUTING.md**](https://github.com/dakk/qlasskit/blob/master/CONTRIBUTING.md) before contributing.

**Comment by CRTejaswi** [comment]
Hi, @dakk !
I'd like to work on this issue as a part of unitaryhack.

**Comment by dakk** [comment]
Hi, wonderful, please go on and let me know if you need anything.

**Comment by CRTejaswi** [comment]
Hi, @dakk! Can you please share a couple of sample python files to be transpiled?

**Comment by dakk** [comment]
You can find some example code in test cases and in the docs; are they ok?

**Comment by tomv42** [comment]
I'll start working on this issue

**Comment by dakk** [comment]
Thank you for the contributions @tomv42 ; I hope you enjoyed working on the qlasskit library: if so, please "star" the project, and tell your quantum friends about qlasskit :)

**Comment by tomv42** [comment]
This was my first experience in open source and I really enjoyed working on qlasskit. I learned a lot. Also, I've already starred the project :)

**Comment by KallieFerguson** [comment]
@tomv42 it doesn't look like you registered for unitaryhack, send me an email at kallie@unitary.fund if you want the bounty.
