### ISSUE TITLE
Request for algorithms!

### ISSUE THREAD

**Issue by dakk** [dakk/qlasskit#32]
- Propose and implement an algorithm in the [`qlasskit.algorithms`](https://github.com/dakk/qlasskit/tree/master/qlasskit/algorithms) package.
- Create a notebook in docs, showcasing the algorithm
- The algorithm have to use one or more `qlassf` functions. 
- The algorithm have to preferably come from a peer-reviewed paper.
- The proposed algorithm have to be approved by the maintainer. 
- Take a look at the [documentation](https://dakk.github.io/qlasskit/algorithms.html) for hints.

The code of the pull request should include:
- the QAlgorithm implemented in the algorithm module
- the test suite with a complete coverage
- one or more notebook in the docs, showing a cool use case

Please read [**CONTRIBUTING.md**](https://github.com/dakk/qlasskit/blob/master/CONTRIBUTING.md) before contributing.

**Comment by dakk** [comment]
Hi @AbdullahKazi500 , thank you for your contribution. Can you show me an example of use-case for the algo using a qlasskit function? 

Anyway, the algorithm should be implemented in the algorithms module; the notebook is only a showcase of the algorithm. Before writing more code, please answer the question above.

**Comment by dakk** [comment]
> hi @dakk I can possibly try but since QPE is an advance and complex algo I dont know if we can extend it to a use case given qlasskit is in a beta stage do you want me to try it out

Yes, try it out. 



> in my notebook I have given a basic demo of the QPE circuit using qlasskit function

In your notebook you just the QAlgorithm of QPE, you're not using it. You should instead put the QAlgorithm implementation in a proper file in the algorithms module, while put a demo in the notebook. 

But before writing more code, please show me an example of use-case for the algo using a qlasskit function, so I can determine in the algorithm you proposed is suitable for qlasskit.

**Comment by dakk** [comment]
> ok Suppose we have a simple quantum circuit that applies a single-qubit gate U to an ancillary qubit in the state ∣+⟩, where U is a phase gate with an unknown phase θ. We want to estimate this phase θ. this is a basic use case @dakk

Ok thanks; I'm sorry but I don't think QPE meets the issue requirements. Thank you for the proposal anyway!

**Comment by dakk** [comment]
No, I'm sorry but the requirements should be met in order to solve the issue. Anyway, if you have any other proposal let me know!

**Comment by dakk** [comment]
Yes, like I did for Grover search; in the use case, I used Grover implemented inside qlasskit, in order to search for a solution of an oracle. This oracle is built using qlasskit, for example searching for a sudoku puzzle solution.

https://dakk.github.io/qlasskit/example_grover_sudoku.html

Like I did for Grover, the final work of the issue should include:
- the QAlgorithm implemented in the algorithm module
- the test suite with a complete coverage
- a notebook in the docs, showing a cool use case

**Comment by divshacker** [comment]
Hey, I have made a PR and it got successfully merged.

**Comment by dakk** [comment]
Thank you divshacker for the contribution!
